version: "3.8"

networks:
  kafka:
    name: kafka

services:
  zookeeper-1:
    container_name: zookeeper-1
    image: pancudaniel7/zookeeper:2.7.0
    build:
      context: ./zookeeper
    volumes:
      - ./config/zookeeper-1/zookeeper.properties:/kafka/config/zookeeper.properties
      - ~/.data/zookeeper-1/:/tmp/zookeeper/
    networks:
      - kafka
  kafka-1:
    container_name: kafka-1
    image: pancudaniel7/kafka:3.1.0
    depends_on:
      - zookeeper-1
    build:
      context: .
    volumes:
      - ./config/kafka-1/server.properties:/kafka/config/server.properties
      - ~/.data/kafka-1/:/tmp/kafka-logs/
    networks:
      - kafka
  kafka-2:
    container_name: kafka-2
    image: pancudaniel7/kafka:3.1.0
    depends_on:
      - zookeeper-1
    build:
      context: .
    volumes:
      - ./config/kafka-2/server.properties:/kafka/config/server.properties
      - ~/.data/kafka-2/:/tmp/kafka-logs/
    networks:
      - kafka
  kafka-3:
    container_name: kafka-3
    image: pancudaniel7/kafka:3.1.0
    depends_on:
      - zookeeper-1
    build:
      context: .
    volumes:
      - ./config/kafka-3/server.properties:/kafka/config/server.properties
      - ~/.data/kafka-3/:/tmp/kafka-logs/
    networks:
      - kafka
  provisioning:
    container_name: kafka-provisioning
    image: pancudaniel7/kafka-provisioning:1.0.0
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    build:
      context: ./provisioning
    environment:
      - "kafka.bootstrap.servers=kafka-1:9092,kafka-2:9092,kafka-3:9092"
    networks:
      - kafka